### PR TITLE
Added assignment details & submission link to README.

### PR DESCRIPTION
**Pull request by john-osullivan**

### CODE REVIEW

**Comment by hariharsubramanyam** [comment]
LGTM, feel free to merge

**Comment by john-osullivan** [comment]
Apparently I don't have write access to the repository -- could you please accept this PR?

**Comment by john-osullivan** [comment]
Thanks man (y)

**Comment by hariharsubramanyam** [comment]
No problem! I think I gave you an invite to the wrong repo, now I invited you to this repo

**Pull request merged**
